<a href="https://colab.research.google.com/github/AlexMcClung/profgalloway/blob/master/scratchpad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_excel('https://github.com/AlexMcClung/profgalloway/raw/master/galloway-data.xlsx')

df.sample(10)

                  Institution Name  ...  Prof G Categorization
100              Furman University  ...               Struggle
417               Wesleyan College  ...               Struggle
219                   Reed College  ...               Struggle
331  University of Hawaii at Manoa  ...                Survive
201    Ohio University-Main Campus  ...                 Thrive
328          University of Florida  ...                Survive
132               Houghton College  ...               Struggle
230      Rutgers University-Camden  ...                Survive
39      Carnegie Mellon University  ...                Survive
165             Macalester College  ...                 Perish

[10 rows x 31 columns]